Sync with CachyOS
Signed-off-by: Piotr Gorski <lucjan.lucjanov@gmail.com>

diff --git a/devtools-git/0001-makechrootpkg-add-paccache-flag.patch b/devtools-git/0001-makechrootpkg-add-paccache-flag.patch
--- a/devtools-git/0001-makechrootpkg-add-paccache-flag.patch
+++ b/devtools-git/0001-makechrootpkg-add-paccache-flag.patch
@@ -1,4 +1,4 @@
-From 75db029a457bbcbd60ccf50d0eb601581e483115 Mon Sep 17 00:00:00 2001
+From 9fc61fc4325cfe36dc86353137eb38041c79275f Mon Sep 17 00:00:00 2001
 From: Vladislav Nepogodin <nepogodin.vlad@gmail.com>
 Date: Tue, 28 May 2024 14:40:59 +0400
 Subject: [PATCH] makechrootpkg: add paccache flag
@@ -6,11 +6,11 @@ Subject: [PATCH] makechrootpkg: add paccache flag
 if the flag is given, then pass it to the arch-nspawn to build the
 package with.
 ---
- src/makechrootpkg.in | 8 +++++++-
- 1 file changed, 7 insertions(+), 1 deletion(-)
+ src/makechrootpkg.in | 17 +++++++++++------
+ 1 file changed, 11 insertions(+), 6 deletions(-)
 
 diff --git a/src/makechrootpkg.in b/src/makechrootpkg.in
-index 9df14e8..c63fe0f 100644
+index 9df14e8..1d157b5 100644
 --- a/src/makechrootpkg.in
 +++ b/src/makechrootpkg.in
 @@ -75,6 +75,7 @@ usage() {
@@ -21,6 +21,15 @@ index 9df14e8..c63fe0f 100644
  	echo '-I <pkg>          Install a package into the working copy of the chroot'
  	echo '-l <copy>         The directory to use as the working copy of the chroot'
  	echo '                  Useful for maintaining multiple copies'
+@@ -150,7 +151,7 @@ install_packages() {
+ 	pkgnames=("${install_pkgs[@]##*/}")
+ 
+ 	cp -- "${install_pkgs[@]}" "$copydir/root/"
+-	arch-nspawn "$copydir" "${bindmounts_ro[@]}" "${bindmounts_rw[@]}" "${bindmounts_tmpfs[@]}" \
++	arch-nspawn "${cache_dirs[@]}" "$copydir" "${bindmounts_ro[@]}" "${bindmounts_rw[@]}" "${bindmounts_tmpfs[@]}" \
+ 		pacman -U --noconfirm --ask=4 -- "${pkgnames[@]/#//root/}"
+ 	ret=$?
+ 	rm -- "${pkgnames[@]/#/$copydir/root/}"
 @@ -293,7 +294,7 @@ move_products() {
  }
  # }}}
@@ -30,25 +39,53 @@ index 9df14e8..c63fe0f 100644
  	case "$arg" in
  		c) clean_first=1 ;;
  		D) bindmounts_ro+=("--bind-ro=$OPTARG") ;;
-@@ -308,6 +309,7 @@ while getopts 'hcur:I:l:nCTD:d:U:x:t:' arg; do
+@@ -308,6 +309,10 @@ while getopts 'hcur:I:l:nCTD:d:U:x:t:' arg; do
  		T) temp_chroot=1; copy+="-$$" ;;
  		U) makepkg_user="$OPTARG" ;;
  		x) inspect="$OPTARG" ;;
-+		P) cache_dirs+=("$OPTARG") ;;
++		P)
++		   cache_dirs+=("-c")
++		   cache_dirs+=("$OPTARG")
++		   ;;
  		h|*) usage ;;
  	esac
  done
-@@ -396,6 +398,10 @@ nspawn_build_args=(
+@@ -367,7 +372,7 @@ if [[ ! -d $copydir ]] || (( clean_first )); then
+ 	sync_chroot "$chrootdir" "$copydir" "$copy"
+ fi
+ 
+-(( update_first )) && arch-nspawn "$copydir" \
++(( update_first )) && arch-nspawn "${cache_dirs[@]}" "$copydir" \
+ 		"${bindmounts_ro[@]}" "${bindmounts_rw[@]}" "${bindmounts_tmpfs[@]}" \
+ 		pacman -Syuu --noconfirm
+ 
+@@ -396,7 +401,7 @@ nspawn_build_args=(
  	"${bindmounts_tmpfs[@]}"
  )
  
-+if (( ${#cache_dirs[@]} != 0 )); then
-+    nspawn_build_args+=("${cache_dirs[@]}")
-+fi
-+
- if arch-nspawn "$copydir" \
+-if arch-nspawn "$copydir" \
++if arch-nspawn "${cache_dirs[@]}" "$copydir" \
  	"${nspawn_build_args[@]}" \
  	/chrootbuild "${makepkg_args[@]}"
+ then
+@@ -413,7 +418,7 @@ if [[ $inspect == always ]] || ( [[ $inspect == failure ]] && (( ret != 0 )) );
+ 	else
+ 		error "Build failed, inspecting %s" "$copydir"
+ 	fi
+-	arch-nspawn "$copydir" \
++	arch-nspawn "${cache_dirs[@]}" "$copydir" \
+ 		"${nspawn_build_args[@]}" \
+ 		--user=builduser \
+ 		--chdir=/build
+@@ -444,7 +449,7 @@ else
+ 		for remotepkg in "${remotepkgs[@]}"; do
+ 			if [[ $remotepkg != file://* ]]; then
+ 				msg2 "Downloading current versions"
+-				arch-nspawn "$copydir" pacman --noconfirm -Swdd "${pkgnames[@]}"
++				arch-nspawn "${cache_dirs[@]}" "$copydir" pacman --noconfirm -Swdd "${pkgnames[@]}"
+ 				mapfile -t remotepkgs < <(pacman --config "$copydir"/etc/pacman.conf \
+ 					--dbpath "$copydir"/var/lib/pacman \
+ 					-Sddp "${pkgnames[@]}")
 -- 
 2.45.1.145.g83f1add914
 
